#!/bin/bash
# Provision VM

helpme(){
        echo "Usage: $0 [hostname.sudo.net] [number-of-cpus] [mb of memory] [Optional: rhel|fedora|ubuntu|debian] [Optional: pcidss|apache|quarkus|aap]"
	exit 0
}

if [ "$#" -eq 0 ]
then
	helpme
fi

case $1 in
	*help)
		helpme
	;;
esac

vm_hostname=$1
vm_cpu=$2
vm_mem=$3

# Customize
dc_home="/home/mglantz/code/ansible/localdc"
# For RHEL this is the raw KVM install image downloadable from https://access.redhat.com
vm_template="$dc_home/rhel92-raw.qcow2"
vm_image="$dc_home/vms/${vm_hostname}.qcow2"
vm_ssh_key="/home/youruser/.ssh/id_rsa.pub"
# End of customize

case $4 in
	rhel)
		vm_template="$dc_home/rhel92-raw.qcow2"
	;;
	fedora)
		vm_template="$dc_home/fedora-raw.qcow2"
	;;
	ubuntu)
		vm_template="$dc_home/ubuntu.qcow2"
	;;
	debian)
		vm_template="$dc_home/debian-raw.qcow2"
	;;
        breakable)
                vm_template="$dc_home/oraclelinux-raw.qcow"
        ;;

	*)
		vm_template="$dc_home/rhel92-raw.qcow2"
	;;
esac

cp $vm_template $vm_image

# Prepare VM-image
virt-sysprep --hostname $vm_hostname --enable customize -a $vm_image --ssh-inject root:file:$vm_ssh_key

# Create and startup VM
cd $dc_home
ansible-playbook provision.yml -e vm_image_name=$(echo $vm_image|sed 's/.qcow2//g') -e vm_name=$vm_hostname -e vm_vcpus=$vm_cpu -e vm_ram_mb=$vm_mem -e vm_net=default

echo $vm_hostname >$dc_home/tmpinventory

# Wait for system to come up
while true
do
	ssh -o StrictHostKeyChecking=no -q root@$vm_hostname exit
	if [ "$?" -eq 0 ]
	then
		echo "$vm_hostname is up, initiating setup."
		break
	else
		echo "Waiting for $vm_hostname to come up."
		sleep 1
	fi
done

# Register to RHN
if [ "$vm_template" = "$dc_home/rhel92-raw.qcow2" ]
then
	ansible-playbook -i $dc_home/tmpinventory setup.yml
fi

# Optional config
case $4 in
	pcidss)
		ansible-playbook -i $dc_home/tmpinventory pcidss.yml
	;;
	apache)
		ansible-playbook -i $dc_home/tmpinventory apache.yml
	;;
	quarkus)
		ansible-playbook -i $dc_home/tmpinventory quarkus.yml
	;;

	aap)
		ansible-playbook -i $dc_home/tmpinventory aap.yml
	;;
esac

